# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.gitlab.com/qm64/packer/toolchain:latest

stages:
  - validate
  - apply
  - post-apply

all:validate:
  stage: validate
  script:
    - make -C packer validate
    - make -C configuration validate
    - make -C infrastructure validate

infrastructure:apply:
  stage: apply
  script:
    - make -C infrastructure apply
  only:
    - master 

packer:build:
  stage: apply 
  script:
    - make -C packer build
  when: manual

vault:renew:
  stage: validate
  script:
    - vault token renew -increment=360h > /dev/null
  only:
    - master
    - schedules

vault:manual_renew:
  stage: post-apply
  script:
    - vault token renew -increment=360h > /dev/null
  when: manual

vault:panic:
  stage: post-apply
  script:
    - make panic
  when: manual
