# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.gitlab.com/qm64/packer/toolchain:latest

stages:
  - renew
  - validate
  - apply
  - post-apply

terraform:validate:
  stage: validate
  script:
    - make tf_validate # plan is not possible due to manual work required.

vault:renew:
  stage: renew
  script:
    - vault token renew -increment=360h > /dev/null
  only:
    - master
    - schedules

vault:manual_renew:
  stage: post-apply
  script:
    - vault token renew -increment=360h > /dev/null
  when: manual

vault:panic:
  stage: post-apply
  script:
    - make panic
  when: manual