# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.gitlab.com/siderus/packer/toolchain:latest

stages:
  - validation
  - deploy
  - post-deploy

vault:renew:
  stage: post-deploy
  script:
    - vault token renew -increment=360h > /dev/null
  only:
    - master
    - schedules

vault:manual_renew:
  stage: post-deploy
  script:
    - vault token renew -increment=360h > /dev/null
  when: manual

vault:panic:
  stage: post-deploy
  script:
    - make -C vault panic
  when: manual